# mWizard FreeBSD Makefile

PREFIX ?= /usr/local
MANDIR = $(PREFIX)/man
RCDIR = $(PREFIX)/etc/X11
# Only used to clear away the app-defaults file versions before 1.2
# installed; appearance is in the style file now. See doc/STYLE.md.
APPLRESDIR = $(PREFIX)/etc/X11/app-defaults

INCDIRS = -I/usr/local/include 
LIBDIRS = -L/usr/local/lib

CFLAGS += -Wall $(INCDIRS)

.include "common.mf"

install: common_install
