# mWizard SunOS Makefile

PREFIX = /usr
MANDIR = /usr/share/man
RCDIR = /usr/lib/X11

# Only used to clear away the app-defaults file versions before 1.2
# installed; appearance is in the style file now. See doc/STYLE.md.
APPLRESDIR = /usr/lib/X11/app-defaults

CC = gcc
CFLAGS = -O2 -Wall $(INCDIRS)

include common.mf

install:
	install -m 775 -f $(PREFIX)/bin mwizard
	install -m 664 -f $(MANDIR)/man1 mwizard.1
	install -m 664 -f $(MANDIR)/man4 mwizardrc.4
	install -m 775 -d $(RCDIR)
	install -m 664 -f $(RCDIR) system.mwizardrc
	install -m 664 -f $(RCDIR) system.mstylesrc
	install -m 664 -f $(RCDIR) stalonetrayrc
