# mWizard Linux Makefile

# Installation prefix. Typically /usr or /usr/local.
PREFIX = /usr
MANDIR = $(PREFIX)/share/man

# X11 configuration directory.
# On recent Linuxen it's usually either /etc/X11, /usr/share/X11
# or less likely /usr/lib/X11. Some symlink them one way or another.
RCDIR = /etc/X11

# Only used to clear away the app-defaults file versions before 1.2
# installed; appearance is in the style file now. See doc/STYLE.md.
APPLRESDIR = $(RCDIR)/app-defaults

# Usually nothing needs to be changed beyond this point
INCDIRS = -I/usr/local/include 
LIBDIRS = -L/usr/local/lib

CFLAGS = -O2 -Wall $(INCDIRS)

include common.mf

install: common_install
