# mWizard generic Makefile

PREFIX = /usr
MANDIR = $(PREFIX)/share/man
RCDIR = /etc/X11
# Only used to clear away the app-defaults file versions before 1.2
# installed; appearance is in the style file now. See doc/STYLE.md.
APPLRESDIR = /etc/X11/app-defaults

INCDIRS = -I/usr/local/include -I/usr/X11R6/include
LIBDIRS = -L/usr/local/lib -L/usr/X11R6/lib

CFLAGS = -O2 -Wall $(INCDIRS)

include common.mf

install: common_install
