# mWizard OpenBSD Makefile

PREFIX = /usr/local
MANDIR = /usr/local/man
RCDIR = /usr/X11R6/lib/X11
# Only used to clear away the app-defaults file versions before 1.2
# installed; appearance is in the style file now. See doc/STYLE.md.
APPLRESDIR = /usr/X11R6/lib/X11/app-defaults

INCDIRS = -I/usr/X11R6/include -I/usr/local/include
LIBDIRS = -L/usr/X11R6/lib -L/usr/local/lib

CFLAGS = -O2 -Wall $(INCDIRS)

.c.o:
	$(CC) $(CFLAGS) $(DEFINES) $(INCDIRS) -c -o $(@D)/$(@F) $<

include common.mf

install: common_install
